# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 11.0.7
    - name: Generate java classes
      run: ./generate-proto-java-code.sh

    - name: Build step
      run: ./compile_proto_java.sh 

    - name: Bump version and push tag
      id: bump_version
      uses: getOyster/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master

    - name: Publishing java version
      run:  ./gradle-6.4.1/bin/gradle publish -d -Pversion="${{ steps.bump_version.outputs.tag }}"
      env:
        ARTIFACT_USERNAME: ${{ github.actor }}
        ARTIFACT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
